import { Candidate } from './candidate.interface';

export const presidentialCandidates: Candidate[] = [
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'ACCION POPULAR',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRESIDENTE DE LA REPUBLICA',
        'N°': '1',
        'Primer apellido': 'BARNECHEA',
        'Segundo apellido': 'GARCIA',
        Prenombres: 'ISAAC ALFREDO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'ACCION POPULAR',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRIMER VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '2',
        'Primer apellido': 'GARCIA',
        'Segundo apellido': 'BELAUNDE',
        Prenombres: 'VICTOR ANDRES',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'ACCION POPULAR',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'SEGUNDO VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '3',
        'Primer apellido': 'DEL AGUILA',
        'Segundo apellido': 'MOROTE',
        Prenombres: 'RICARDO EDMUNDO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PERU POSIBLE',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRESIDENTE DE LA REPUBLICA',
        'N°': '1',
        'Primer apellido': 'TOLEDO',
        'Segundo apellido': 'MANRIQUE',
        Prenombres: 'ALEJANDRO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PERU POSIBLE',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRIMER VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '2',
        'Primer apellido': 'AYAIPOMA',
        'Segundo apellido': 'ALVARADO',
        Prenombres: 'FERNANDO MARCIAL',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PERU POSIBLE',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'SEGUNDO VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '3',
        'Primer apellido': 'OMONTE',
        'Segundo apellido': 'DURAND',
        Prenombres: 'MARIA DEL CARMEN',
        Sexo: 'Femenino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PARTIDO POLITICO ORDEN',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRESIDENTE DE LA REPUBLICA',
        'N°': '1',
        'Primer apellido': 'FLORES ARAOZ',
        'Segundo apellido': 'ESPARZA',
        Prenombres: 'ANTERO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PARTIDO POLITICO ORDEN',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRIMER VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '2',
        'Primer apellido': 'MUCHO',
        'Segundo apellido': 'MAMANI',
        Prenombres: 'ROMULO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PARTIDO POLITICO ORDEN',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'SEGUNDO VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '3',
        'Primer apellido': 'BOTTON',
        'Segundo apellido': 'ESTRADA',
        Prenombres: 'MERY LUCY',
        Sexo: 'Femenino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'FUERZA POPULAR',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRESIDENTE DE LA REPUBLICA',
        'N°': '1',
        'Primer apellido': 'FUJIMORI',
        'Segundo apellido': 'HIGUCHI',
        Prenombres: 'KEIKO SOFIA',
        Sexo: 'Femenino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'FUERZA POPULAR',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRIMER VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '2',
        'Primer apellido': 'CHLIMPER',
        'Segundo apellido': 'ACKERMAN',
        Prenombres: 'JOSE',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'EL FRENTE AMPLIO POR JUSTICIA, VIDA Y LIBERTAD',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRESIDENTE DE LA REPUBLICA',
        'N°': '1',
        'Primer apellido': 'MENDOZA',
        'Segundo apellido': 'FRISCH',
        Prenombres: 'VERONIKA FANNY',
        Sexo: 'Femenino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'EL FRENTE AMPLIO POR JUSTICIA, VIDA Y LIBERTAD',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRIMER VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '2',
        'Primer apellido': 'ARANA',
        'Segundo apellido': 'ZEGARRA',
        Prenombres: 'MARCO ANTONIO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'EL FRENTE AMPLIO POR JUSTICIA, VIDA Y LIBERTAD',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'SEGUNDO VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '3',
        'Primer apellido': 'FAIRLIE',
        'Segundo apellido': 'REINOSO',
        Prenombres: 'ALAN CARSOL BERNABE',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'FRENTE ESPERANZA',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRESIDENTE DE LA REPUBLICA',
        'N°': '1',
        'Primer apellido': 'OLIVERA',
        'Segundo apellido': 'VEGA',
        Prenombres: 'LUIS FERNANDO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'FRENTE ESPERANZA',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRIMER VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '2',
        'Primer apellido': 'CUARESMA',
        'Segundo apellido': 'SANCHEZ',
        Prenombres: 'CARLOS RICARDO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'FRENTE ESPERANZA',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'SEGUNDO VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '3',
        'Primer apellido': 'AVELLANEDA',
        'Segundo apellido': 'SOTO',
        Prenombres: 'JUANA NATIVIDAD',
        Sexo: 'Femenino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PROGRESANDO PERU',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRESIDENTE DE LA REPUBLICA',
        'N°': '1',
        'Primer apellido': 'HILARIO',
        'Segundo apellido': 'ESCOBAR',
        Prenombres: 'MIGUEL WALTER',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PROGRESANDO PERU',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRIMER VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '2',
        'Primer apellido': 'PONCE',
        'Segundo apellido': 'AYALA',
        Prenombres: 'MANUEL EDUARDO JULIO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PROGRESANDO PERU',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'SEGUNDO VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '3',
        'Primer apellido': 'PAREJA',
        'Segundo apellido': 'GARCIA',
        Prenombres: 'SILVIA LUZ',
        Sexo: 'Femenino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'DEMOCRACIA DIRECTA',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRESIDENTE DE LA REPUBLICA',
        'N°': '1',
        'Primer apellido': 'SANTOS',
        'Segundo apellido': 'GUERRERO',
        Prenombres: 'GREGORIO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'DEMOCRACIA DIRECTA',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRIMER VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '2',
        'Primer apellido': 'ALCANTARA',
        'Segundo apellido': 'PAREDES',
        Prenombres: 'ANDRES AVELINO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'DEMOCRACIA DIRECTA',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'SEGUNDO VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '3',
        'Primer apellido': 'CHIPANA',
        'Segundo apellido': 'HUANCA',
        Prenombres: 'SIMON',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PERUANOS POR EL KAMBIO',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRESIDENTE DE LA REPUBLICA',
        'N°': '1',
        'Primer apellido': 'KUCZYNSKI',
        'Segundo apellido': 'GODARD',
        Prenombres: 'PEDRO PABLO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PERUANOS POR EL KAMBIO',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'PRIMER VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '2',
        'Primer apellido': 'VIZCARRA',
        'Segundo apellido': 'CORNEJO',
        Prenombres: 'MARTIN ALBERTO',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'PERUANOS POR EL KAMBIO',
        'Tipo Organización Política': 'PARTIDO POLÍTICO',
        Cargo: 'SEGUNDO VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '3',
        'Primer apellido': 'ARAOZ',
        'Segundo apellido': 'FERNANDEZ',
        Prenombres: 'MERCEDES ROSALBA',
        Sexo: 'Femenino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'ALIANZA POPULAR',
        'Tipo Organización Política': 'ALIANZA ELECTORAL',
        Cargo: 'PRESIDENTE DE LA REPUBLICA',
        'N°': '1',
        'Primer apellido': 'GARCIA',
        'Segundo apellido': 'PEREZ',
        Prenombres: 'ALAN GABRIEL LUDWIG',
        Sexo: 'Masculino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'ALIANZA POPULAR',
        'Tipo Organización Política': 'ALIANZA ELECTORAL',
        Cargo: 'PRIMER VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '2',
        'Primer apellido': 'FLORES',
        'Segundo apellido': 'NANO',
        Prenombres: 'LOURDES CELMIRA ROSARIO',
        Sexo: 'Femenino',
    },
    {
        'Distrito Electoral': 'NACION',
        'Organización Política': 'ALIANZA POPULAR',
        'Tipo Organización Política': 'ALIANZA ELECTORAL',
        Cargo: 'SEGUNDO VICEPRESIDENTE DE LA REPUBLICA',
        'N°': '3',
        'Primer apellido': 'SALAZAR',
        'Segundo apellido': 'MOROTE',
        Prenombres: 'DAVID ABRAHAM',
        Sexo: 'Masculino',
    },
];